#!/bin/bash
systemctl stop bluetooth.service
systemctl stop connman.service
insmod /cfg80211.ko
insmod /ath.ko
insmod /ath6kl.ko
sleep 5
rfkill unblock all
/usr/bin/bcattach &
sleep 15
rfkill unblock all
hciconfig hci0 up
systemctl start bluetooth.service
systemctl start connman.service
